version: '3.4'

services:
  pms.server:
    image: ${DOCKER_REGISTRY-}pmsserver
    build:
      context: .
      dockerfile: PMS.Server/Dockerfile
    container_name: pms-server-container
    ports:
        - 80:80
        - 443:443

  seq:
    image: datalust/seq
    container_name: seq-container
    volumes:
        - seq-data:/data
    environment:
        # TODO: Setup a secured version of Seq
        ACCEPT_EULA: Y
    ports:
        - 5050:80

  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      # TODO: Use the POSTGRES_PASSWORD_FILE environment variable so that the password isn't commited
      POSTGRES_PASSWORD: temppw
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256

volumes:
  seq-data:
  db-data:
